Add 'hoverMode' attribute
TonyGermaneri/canvas-datagrid pull request #350
Opened 2021-03-08 09:35 UTC by twojtylak

to enable hover effect on whole row (instead of single cell)

Fixes issue #.

Changes proposed in this pull request:

- 
- 
-

2021-03-08 12:20 UTC, ndrsn requested changes
Great! Just a minor addition requested in the documentation for `hoverMode`

2021-03-08 12:20 UTC, ndrsn commented on lib/docs.js
> + * @param {string} [args.hoverMode='cell'] - Can be 'cell', or 'row'.
I would add:

```
This setting dictates whether to highlight either the individual cell, or the entire row when hovering over a cell.
```

2021-03-08 12:54 UTC, merged

2021-03-08 12:55 UTC, ndrsn commented
Super, thanks for this. I'll release a new version with this later today or tonight, hopefully.

2021-03-08 13:35 UTC, twojtylak commented
@ndrsn yeah, thank you

2021-03-11 01:07 UTC, ndrsn commented
Released in 0.3.4