Allowing a tree grouping along columns
TonyGermaneri/canvas-datagrid pull request #453
Opened 2021-12-18 13:33 UTC by xianzhi3

Fixes issue #.

Changes proposed in this pull request:

- 
- 
-

2021-12-19 00:59 UTC, david542542 commented
@xianzhi3 + @ndrsn looks very good to me: https://90zfd.csb.app/. Nice work.

2021-12-20 09:16 UTC, ndrsn commented
This seems like a bug?

![CleanShot 2021-12-20 at 10 14 47](https://user-images.githubusercontent.com/950979/146742744-c2c894e5-0956-4709-88ef-c18f748067da.gif)

2021-12-20 11:58 UTC, xianzhi3 commented
let me check

2021-12-21 14:36 UTC, xianzhi3 commented
it looks like the issue is not one that is related with the tree group. When you resize the columns, it is only scrolled right.

2021-12-21 19:40 UTC, david542542 commented
@xianzhi3 that's wrong. Here is a video. Please fix all issues mentioned in the video: https://gyazo.com/9547e615a7ead1e46a0c34388fee8355

- Dragging right should only change the right-side width of an item
- Dragging left should only change the left-side width of a grid

However! I think this may already be working properly, and there is a bug with the scroll-bar, so I think if you examine the scroll-bar positioning (and it's calculation of where to put it) that is where the issue comes from.

2021-12-21 19:42 UTC, david542542 commented
Yes, @xianzhi3 + @ndrsn I think my suspicion is correct. It is a scroll-bar positioning issue. Nonetheless, please fix this:

https://gyazo.com/cc76d70142c889b6003b153779b66729

2021-12-22 00:29 UTC, xianzhi3 commented
ok, let me check scroll-bar part

2021-12-22 01:35 UTC, xianzhi3 commented
I fixed the bug. You can have a test at the link.
https://90zfd.csb.app/

2022-01-05 15:56 UTC, ndrsn commented
@xianzhi3 , apologies for getting back to you so late on this. Thanks for all the work and the bugfix! I have noticed something else, though:

![CleanShot 2022-01-05 at 16 37 03](https://user-images.githubusercontent.com/950979/148245134-ec22a208-d76b-4971-b86d-da7efaf9c1f6.gif)

When collapsing, I wouldn't expect the value immediately below the group handle to disappear — or is this as intended?

Another issue: when typing a value below a column tree group, it seems to not render, although when editing the value seems to still exist on that cell:

![CleanShot 2022-01-05 at 16 40 43](https://user-images.githubusercontent.com/950979/148245760-1839fa91-e9c9-46d7-8c94-4e957a5782fd.gif)

Finally, when typing next to the tree, it seems to delete cell values. Not sure how this works with pre-existing cell values, though...

![CleanShot 2022-01-05 at 16 54 15](https://user-images.githubusercontent.com/950979/148247988-ba454f90-c1dd-4e91-9c20-514a0a2944b3.gif)

2022-01-05 16:13 UTC, ndrsn requested changes
Love the work in general (!), it's nicely structured and clear, but have some minor comments/requests.

Also, would it be possible to add tests for this functionality, similar to how @hangxingliu has done in #443 ? This will make refactoring down the road a whole lot easier/safer :)

I'm not sure how exactly that would look but can help with pointers if you need assistance.

2022-01-05 16:13 UTC, ndrsn commented on lib/intf.js
> +  self.celltree = {
For consistency I think `cellTree` would be better?

2022-01-05 16:13 UTC, ndrsn commented on lib/draw.js
> +    const pc = rowTree ? tree.parentCount : 0;
Can we write out variable names like `pc/rc/mt/mr/ml` etc to something more descriptive?

No hard rule that _all_ need to be written out (I mean, stuff like `x` and `y` are obvious, as are counters like `i`), but while it's a little more annoying to write the code, writing the more semantic variables out makes it _a lot_ easier to read and debug afterwards

2022-01-05 23:36 UTC, xianzhi3 commented
"When collapsing, I wouldn't expect the value immediately below the group handle to disappear — or is this as intended?"
it is collapsed with options I added because the table is pivot one.

2022-01-05 23:48 UTC, david542542 commented
@xianzhi3 no, he means this: https://gyazo.com/6162bf0bf7045a44d4d03fe27412b1d2

2022-01-07 09:37 UTC, xianzhi3 commented
@ndrsn I fixed the bugs above and pushed the changes

2022-01-07 09:42 UTC, xianzhi3 commented
https://user-images.githubusercontent.com/78894564/148524779-688faeb4-228e-481d-9bf1-3583946aeedd.mp4

Here is a video for the fix

2022-01-07 10:51 UTC, ndrsn commented
Awesome work, @xianzhi3! Looks really good 👍 

One last thing I'm still seeing is the disappearing value below the column group handles:

![CleanShot 2022-01-07 at 11 50 39](https://user-images.githubusercontent.com/950979/148533354-d88d3983-e1e7-4087-85a0-3ec7d043ebd6.gif)

Is this how Excel does it as well? It seems counterintuitive.

2022-01-07 20:39 UTC, david542542 commented
Hi @ndrsn this should be the expected behavior for a pivot table. Here would be an example from Excel: https://gyazo.com/7cd2a84cecc9c506ff8fc2bfa2a289c9.

I suppose the best way to describe it would be to 'hide details' and summarize to a higher level. For example, if I have `Year > Month` collapsing to the Year would show the value at the year-level and hide the details of the month-level.

2022-01-08 14:35 UTC, ndrsn commented
@david542542 correct me if I'm wrong, but I think the difference between this implementation and what I see in your Excel example, is that the column immediately below the plus icon remains the same, whereas in Excel the column is replaced with the one at the end of the column group.

This is hard to describe in text, so take 0:55 in your video, for example. Once the group is collapsed, the values in column P are replaced with those of column W (`AUD` and `3.92` disappear).

Before collapsing:
![CleanShot 2022-01-08 at 15 32 58@2x](https://user-images.githubusercontent.com/950979/148648092-508ca594-2ff8-45b5-9c03-cd6821628197.png)

After collapsing:
![CleanShot 2022-01-08 at 15 33 50@2x](https://user-images.githubusercontent.com/950979/148648126-d670c8b3-cc84-400c-8de7-a4ef8ad7a591.png)

 In the implementation in this PR, only the value under the icon disappears, but the column values in other rows remain?

2022-01-08 21:09 UTC, david542542 commented
@ndrsn ah yes I see. let me write up an example for @xianzhi3 to fix.

2022-01-10 02:18 UTC, david542542 commented
@xianzhi3 I have added a sample Excel file and here's a video of how I want you to test: https://gyazo.com/902d4f84a14b3fdf60e610593d009cba. It's going to be tedious, but for the pivot table (you can hard-code the data that's fine) I want you to (1) collapse all-columns and make sure the values are the exact same as excel; then (2) collapse all-rows and make sure they're the same as excel; and then (3) collapse both and make sure they're the same. The testing will be tedious, but yes this is what you'll need to do in your video to confirm it's working properly.

[TestPivot.xlsx](https://github.com/TonyGermaneri/canvas-datagrid/files/7836516/TestPivot.xlsx)

2022-01-10 17:02 UTC, xianzhi3 commented
I pushed the changes to the link below.
https://90zfd.csb.app/
Here is a video for that.

https://user-images.githubusercontent.com/78894564/148806913-0f1160bc-8b18-4394-9750-6336fa5b71cb.mp4

2022-01-10 20:52 UTC, ndrsn commented
Excellent, @xianzhi3, thanks so much! This is really great work. Merging!

🎉 🎈 💥

2022-01-10 20:52 UTC, merged

2022-01-10 21:55 UTC, david542542 commented
@xianzhi3 also, let's please fix the context menu now -- it seems to be missing the various Expand/Collapse node options: https://gyazo.com/980b51159c5464a295f7b3076b1ecad9